server:
  port: 9296

spring:
  profiles:
    active: native
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/seyeadamaUASZ/configservice
          clone-on-start: true